site_name: PSPushover
site_description: Send notifications to any device from PowerShell using pushover.net
site_dir: Output/site
repo_url: https://github.com/joshooaj/PSPushover
remote_branch: gh-pages

theme:
  name: material
  icon:
    repo: material/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Light mode

plugins:
  - search
  - awesome-pages
  - privacy
  - social:
      cards_layout_options:
        font_family: Meow Script
        color: "#ffffff"
        background_color: "#4d9bea"

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/joshooaj
      name: joshooaj on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joshooaj
      name: joshooaj on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/joshooaj
      name: joshooaj on GitHub

nav:
  - Home: README.md
  - Commands:
    - ... | flat | en-US/*.md
