name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/Docs.yml
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/Docs.yml
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Test
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap

